<?php
$deckTennis = array(
    array(
        'ID' => 1,
        'name' => 'Racket Man',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 2,
        'name' => 'Serial Lober',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 3,
        'name' => 'Boxing tennis',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 4,
        'name' => 'GOAT Offensive',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 5,
        'name' => 'Sneak Attack',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 6,
        'name' => 'Hawk-eye\'s',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'Watching You'
    ),
    array(
        'ID' => 7,
        'name' => 'Crocodile',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'Dumbdee'
    ),
    array(
        'ID' => 8,
        'name' => 'Hot Shot',
        'PV' => '',
        'type' => 'spell',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 9,
        'name' => 'Power Shot',
        'PV' => '',
        'type' => 'spell',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 10,
        'name' => 'Banana Shot',
        'PV' => '',
        'type' => 'spell',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 11,
        'name' => 'Moonball',
        'PV' => '',
        'type' => 'spell',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 12,
        'name' => 'Lucky Shot',
        'PV' => '',
        'type' => 'spell',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 13,
        'name' => 'Smashing Sisters',
        'PV' => 9,
        'type' => 'special',
        'mana' => 6,
        'power' => 6,
        'description' => 'test de description'
    ),
    array(
        'ID' => 14,
        'name' => 'Filet',
        'PV' => 4,
        'type' => 'bouclier',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 15,
        'name' => 'Lifty',
        'PV' => 4,
        'type' => 'bouclier',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 16,
        'name' => 'Filet',
        'PV' => 4,
        'type' => 'bouclier',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 17,
        'name' => 'Lifty',
        'PV' => 4,
        'type' => 'bouclier',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 18,
        'name' => 'Racket Man',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 19,
        'name' => 'Serial Lober',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    ),
    array(
        'ID' => 20,
        'name' => 'Boxing tennis',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description'
    )
);

$deckAstro = array(
    array(
        'ID' => 1,
        'name' => 'Sirius B',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 2,
        'name' => 'Twins star',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 3,
        'name' => 'Gamma Ray-Girl',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 4,
        'name' => 'White Dwarf',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 5,
        'name' => 'Andromeda',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 6,
        'name' => 'Deep Impact',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'Watching You',
    ),
    array(
        'ID' => 7,
        'name' => 'Fire Ball',
        'PV' => 4,
        'type' => 'spell',
        'mana' => 3,
        'power' => 2,
        'description' => 'Hoooot',
    ),
    array(
        'ID' => 8,
        'name' => 'Mirage Gravitationnel',
        'PV' => '',
        'type' => 'spell',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 9,
        'name' => 'Star Dust',
        'PV' => '',
        'type' => 'spell',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 10,
        'name' => 'Graviton Particle',
        'PV' => '',
        'type' => 'spell',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 11,
        'name' => 'Halley Comet',
        'PV' => '',
        'type' => 'spell',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 12,
        'name' => 'Aurora',
        'PV' => '',
        'type' => 'spell',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 13,
        'name' => 'Super Nova',
        'PV' => 9,
        'type' => 'special',
        'mana' => 6,
        'power' => 6,
        'description' => 'test de description',
    ),
    array(
        'ID' => 14,
        'name' => 'Hoag\'s Object',
        'PV' => 4,
        'type' => 'bouclier',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 15,
        'name' => 'Black Hole',
        'PV' => 4,
        'type' => 'bouclier',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 16,
        'name' => 'Hoag\'s Object',
        'PV' => 4,
        'type' => 'bouclier',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 17,
        'name' => 'Black Hole',
        'PV' => 4,
        'type' => 'bouclier',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 18,
        'name' => 'Sirius B',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 19,
        'name' => 'Twins Star',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    ),
    array(
        'ID' => 20,
        'name' => 'Andromeda',
        'PV' => 4,
        'type' => 'creature',
        'mana' => 3,
        'power' => 2,
        'description' => 'test de description',
    )
);
